// Mocks generated by Mockito 5.0.16 from annotations
// in flutter_classroom/test/src/features/currency_converter/data/services/currency_service_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:flutter_classroom/src/core/services/http_client.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [HttpClient].
///
/// See the documentation for Mockito's code generation for more information.
class HttpClientMock extends _i1.Mock implements _i2.HttpClient {
  HttpClientMock() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<Map<String, dynamic>> httpGet(
          {String? path, Map<String, dynamic>? queryParameters}) =>
      (super.noSuchMethod(
          Invocation.method(
              #httpGet, [], {#path: path, #queryParameters: queryParameters}),
          returnValue:
              Future<Map<String, dynamic>>.value(<String, dynamic>{})) as _i3
          .Future<Map<String, dynamic>>);
  @override
  _i3.Future<Map<String, dynamic>> httpsGet(
          {String? path, Map<String, dynamic>? queryParameters}) =>
      (super.noSuchMethod(
          Invocation.method(
              #httpsGet, [], {#path: path, #queryParameters: queryParameters}),
          returnValue:
              Future<Map<String, dynamic>>.value(<String, dynamic>{})) as _i3
          .Future<Map<String, dynamic>>);
  @override
  String toString() => super.toString();
}
